### ISSUE TITLE
Support gravity and crop/fill for aspect mismatches

### ISSUE THREAD

**Issue by fluffy-critter** [kikito/gamera#10]
Gamera looks pretty great! But there's a use case it doesn't cover that I need, namely being able to specify a camera view based on any arbitrary aspect and having the screen preferentially cover a particular area of it. For example, the incredibly tedious scaling setup code [in one of my games](https://github.com/fluffy-critter/Refactor-Game/blob/dc2fd2c9e00dd357b4fb8c27e10ee484cd2c0274/src/track7/init.lua#L514) sets the screen up to prevent people from peeking ahead, and there's also obvious use cases for cropping the camera's view in case of a mismatch instead.

I would propose that there be an optional configuration stash that gets passed in as a fifth parameter, with options like:

```lua
gamera.new(0, 0, 100, 100, {
    fit = 'grow',
    anchor = {0.5, 1}
})
```

where `fit` can be one of (for example) `grow`, `shrink`, or `stretch`, and `anchor` would give the relative anchor point for the center (defaulting to {0.5,0.5}); so for example the above would crop the camera view to match the aspect with the center point being the center of the bottom edge; on a 16:9 screen your screen coordinates would map to (0,43.75)–(100,100), for example.

As another example, the camera setup for the code I linked to would be:

```lua
gamera.new(-960, -540, 1920, 1080, { fit = 'shrink', anchor = {0.5, 1} });
```

**Comment by kikito** [comment]
This looks very game-specific to me. My recommendation would be implementing a `cameraman` of sorts (some piece of code which abstracts the camera between your game and gamera) and putting those special restrictions there. For now I will close this issue. By the way, apologies for my delay in answering.
