### ISSUE TITLE
After zooming in got error in camera:toWorld(x,y)https://github.com/kikito/gamera/pulse

### ISSUE THREAD

**Issue by DjSapsan** [kikito/gamera#11]
related code:
```
cam = gamera.new(0,0,1010,1010)
wX,wY = cam:toWorld(x,y)
drawSomething(wX,wY)
```
After zooming i got error "attempt to index a nil value" because wX and wY doesn't get values. Program working only in original zoom.

**Comment by flamendless** [comment]
Maybe because your `x` and `y` is nil?

**Comment by DjSapsan** [comment]
Sorry, too late. I dot remember, but x and y was always not a nil. I think problem with a scale. 
Anyway, nevermind, its too late for discussing

**Comment by kikito** [comment]
Thanks for opening the issue in the first place, and apologies for not answering on a timely manner.
