### ISSUE TITLE
black borders

### ISSUE THREAD

**Issue by dezorkic** [kikito/gamera#14]
I am using a tile map as the game map and load it with STI.

The tile map has tiles of 16x16 and the full size is 512x512 (the game world).

I then have a resolution of 768 x 672 for my game window.

The player is located at some location on the map.

Considering I am using a higher resolution (768 x 672), if I were to not touch any scaling
options, the game would be bad because the full map is shown then, that's not what I
want. So, I adjusted a scale of 3, which makes good zoom for my game.

Now using Gamera, I set the cam to my player initial position and that is fine.

If I scroll up or left, the Gamera detects the world boundaries and it doesn't show
the black borders. But.... it doesn't seem to work for right and down, it shows black
borders there. How can I make it stop scrolling considering the scale of 3 and all
the dimensions above? I don't want to see the black borders to the right and down.

Thank you!

**Comment by kikito** [comment]
Hi, this would be much easier to explain with an example code.

What I think is happening is that either your _window_ or your _world_ params are not correct. My biggest suspicion is the world height and/or width. Check those.
