### ISSUE TITLE
Handling screen size changes?

### ISSUE THREAD

**Issue by ravener** [kikito/gamera#16]
Shouldn't there be like a `cam:resize(w, h)` method to be called in `love.resize` for screen size changes?

This specifically applies to Android I'd say because I notice that in `love.load` I have a smaller size given and then right after `love.resize` is called with the correct size, but since most games and all prefer initialization in `love.load` the end result is everything is working with smaller screen size than actually is. Would be good to have a function to just call in the resize method and keep everything updated.

**Comment by ravener** [comment]
Actually ignore the Android part, that one seems to be a bug https://github.com/love2d/love-android/issues/233

But still what if the window is resizable in desktop? How would you ensure the camera is updated.

**Comment by MikuAuahDark** [comment]
Does `cam:setWindow` doesn't work for you?

**Comment by ravener** [comment]
whoops, my bad, I overlooked this, yeah that works perfectly fine.
