### ISSUE TITLE
[bug] clamp in adjustPosition lead camera con't change it position !

### ISSUE THREAD

**Issue by endlesstravel** [kikito/gamera#4]
I just use below code in my game:
`cam = gamera.new(0,0, 800,600) cam:setPosition(100, 100)`

but I debug it found in "gamera:draw" in line 181 which 'self.x self.y' **always** 300 and 400.
it made me crazy untill I delete line 62 in local function "clamp" :santa: , then, everything is ok

However, It isn't a long - term policy.

**Comment by endlesstravel** [comment]
I am figure out what happend.
I am stupid :joy:  to use small size map on gamera system which lead  gamera can't move it position
:joy: Sorry to open a issue

**Comment by kikito** [comment]
Don't beat yourself, you are not stupid, and you are not the first person finding that "problem". You have helped me realize that I should improve the docs so that the params are explained better. Thanks!
