### ISSUE TITLE
Improve documentation about the difference between viewport and world

### ISSUE THREAD

**Issue by kikito** [kikito/gamera#5]
Some people still misunderstand what they mean. The docs need to be better/less confusing. Maybe adding some picture?

**Comment by endlesstravel** [comment]
How about this :

It like a small rectangle limit in a big rectangle where the big rectangle is what you want to draw the whole map or scene, and the small rectangle is decide what you want to show at current time on the big scene.

And the "setWindow" decide the width and height of the small rectangle as well as the position where your want to place your current sence on the game window

and the "setPosition" decide the position of small rectangle in big rectangle( game scene)

**Comment by kikito** [comment]
I think it will work better with graphics. I will try to cook something up. Thanks for your feedback nevertheless!
